// <auto-generated />
namespace ApiPresupuesto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CambiosPremios2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiosPremios2));
        
        string IMigrationMetadata.Id
        {
            get { return "202109282136064_CambiosPremios2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
